resolvendo issue #3
joaovian06/rails-blog pull request #8
Opened 2020-06-04 16:21 UTC by joaovian06

adicionando categorias aos artigos e alterações em todas respectivas views, utilizando FactoryBot.

2020-06-05 13:07 UTC, bzumpano requested changes
@joaovian06 Deixei umas observações de melhoria

2020-06-05 13:07 UTC, bzumpano commented on spec/factories/articles.rb
> +    category { [:scientific, :entertainment, :news].sample }
Aqui podemos usar o `Article.categories.keys.sample` ao invés do _array_ fixo, assim não precisa ficar ajustando sempre que as opções de _category_  mudar.

2020-06-05 13:07 UTC, bzumpano commented on app/controllers/articles_controller.rb
> +    @articles = Article.order(created_at: :desc).page(param_page).per(10)
No trecho `.per(10)` podemos extrair o número `10` para uma constante:
```
PER_PAGE = 10
...
def index
    @articles = Article.order(created_at: :desc).page(param_page).per(5)	    @articles = Article.order(created_at: :desc).page(param_page).per(PER_PAGE)
end
```

Quando temos números "soltos" no código chamamos de _magic numbers_, é ruim pois eles por si não expressam o propósito, atribuindo eles a uma constante conseguimos dizer para o que ele será usado.

Veja esse post demonstrando: https://www.eliotsykes.com/magic-numbers

2020-06-05 13:07 UTC, bzumpano commented on app/models/article.rb
> +  validates :category, presence: true
Faltou criar o teste para essas validações em `spec/article_spec.rb`

2020-06-05 13:07 UTC, bzumpano commented on spec/article_spec.rb
> +  end
Podemos contextualizar esse teste colocando ele dentro de um `describe`, por ex.:

```
describe 'enums' do
  it { is_expected.to define_enum_for(:category).with_values([:scientific, :entertainment, :news]) }
end
```

2020-06-09 11:17 UTC, joaovian06 commented on spec/factories/articles.rb
> +    category { [:scientific, :entertainment, :news].sample }
Realizei a alteração

2020-06-09 11:18 UTC, joaovian06 commented on app/controllers/articles_controller.rb
> +    @articles = Article.order(created_at: :desc).page(param_page).per(10)
Criei a constante que permite facilitar a passagem do parametro de artigos por página.

2020-06-09 11:29 UTC, joaovian06 commented on spec/article_spec.rb
> +  end
ultilizei o `describe` para separar os testes por contexto.

2020-06-09 14:07 UTC, joaovian06 commented on app/models/article.rb
> +  validates :category, presence: true
criei os testes para as validações

2020-06-09 18:15 UTC, bzumpano approved these changes
Só deixei uma sugestão de _ refactor_ ! 👏

2020-06-09 18:15 UTC, bzumpano commented on app/controllers/articles_controller.rb
> +      @articles = Article.order(created_at: :desc).page(param_page).per(5).where(category: filter_param)
Perceba que o trecho `@articles = Article.order(created_at: :desc).page(param_page).per(5)` é executado tanto no `if` quanto no `else`, ou seja, ele é executado sempre. Então podemos extrair ele para fora da condicional, deixando apenas:
```
def index
  @articles = Article.order(created_at: :desc).page(param_page).per(5)
  @articles = @articles.where(category: filter_param) if filter_param.empty?
end
```

2020-06-10 13:07 UTC, joaovian06 commented on app/controllers/articles_controller.rb
> +      @articles = Article.order(created_at: :desc).page(param_page).per(5).where(category: filter_param)
realizada refatoração no código

2020-06-10 13:33 UTC, mhsabino requested changes

2020-06-10 13:33 UTC, mhsabino commented on spec/models/article_spec.rb
> +require 'rails_helper'
Apenas uma refatoração: 

```ruby

require 'rails_helper'

RSpec.describe Article, type: :model do
  let(:article) { FactoryBot.create(:article) }

  describe 'enums' do
    it 'must have one category inside of this array' do
      is_expected.to define_enum_for(:category).with_values([:scientific, :entertainment, :news])
    end
  end

  describe 'validations' do
    describe 'title' do
      it 'must be present in a article' do
        is_expected.to validate_presence_of(:title)
      end
      it 'needs to have 5 caracters in less' do
        expect(article.title.length).to be >= 5
      end
    end

    describe 'category' do
      it 'must be present in a article' do
        is_expected.to validate_presence_of(:category)
      end
    end

    describe 'text' do
      it 'must be present in a article' do
        is_expected.to validate_presence_of(:text)
      end
    end
  end
end

```

Veja se faz sentido esse ajuste e se está funcionando hehehe

2020-06-10 15:51 UTC, joaovian06 commented on spec/models/article_spec.rb
> +require 'rails_helper'
fiz as alterações nos testes

2020-06-11 14:02 UTC, mhsabino approved these changes

2020-06-11 14:02 UTC, merged